name: Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: "plms-clz"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_KEY: ${{secrets.APP_KEY}}
          HD_LOG_CHANNEL: "errorlog"
          HD_DB_CONNECTION: "pgsql"
          HD_BROADCAST_DRIVER: "pusher"
          HD_PUSHER_APP_ID: ${{secrets.PUSHER_APP_ID}}
          HD_PUSHER_APP_KEY: ${{secrets.PUSHER_APP_KEY}}
          HD_PUSHER_APP_SECRET: ${{secrets.PUSHER_APP_SECRET}}
          HD_PUSHER_APP_CLUSTER: ${{secrets.PUSHER_APP_CLUSTER}}
          HD_MIX_PUSHER_APP_KEY: ${{secrets.PUSHER_APP_KEY}}
          HD_MIX_PUSHER_APP_CLUSTER: ${{secrets.PUSHER_APP_CLUSTER}}
          HD_MQTT_HOST: ${{secrets.MQTT_HOST}}
          HD_MAIL_MAILER: smtp
          HD_MAIL_HOST: smtp.gmail.com
          HD_MAIL_PORT: 465
          HD_MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          HD_MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
          HD_MAIL_ENCRYPTION: ssl
          HD_MAIL_FROM_ADDRESS: ${{secrets.MAIL_USERNAME}}
          HD_MAIL_FROM_NAME: "Power Line Monitoring"
          HD_MAPS_KEY: ${{secrets.MAPS_KEY}}
          HD_FIREBASE_KEY: ${{secrets.FIREBASE_KEY}}
